In [ ]:
#Predicting Prices of Used Cars- Multiple Linear Regression Model

#The file ToyotaCorolla.csv contains data on used cars (Toyota Corolla) on sale during late
#summer of 2004 in the Netherlands. It has 1436 records containing details on 38 attributes, including Price, Age, Kilometers, HP, and other specifications. The goal is to predict the
#price of a used Toyota Corolla based on its specifications. Split the data into training (50%), validation (30%), and test
#(20%) datasets. Run a multiple linear regression with the outcome variable Price and predictor variables Age_08_04, KM, Fuel_Type, HP,
#Automatic, Doors, Quarterly_Tax, Mfr_Guarantee, Guarantee_Period, Airco, Automatic_airco, CD_Player, Powered_Windows, Sport_Model, and Tow_Bar.
#a. What appear to be the three or four most important car specifications for predicting the carâ€™s price?
#b. Using metrics you consider useful, assess the performance of the model in predicting prices.

In [1]:
%matplotlib inline
from pathlib import Path

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, Lasso, Ridge, LassoCV, BayesianRidge
import statsmodels.formula.api as sm
import matplotlib.pylab as plt

from dmba import regressionSummary, exhaustive_search
from dmba import backward_elimination, forward_selection, stepwise_selection
from dmba import adjusted_r2_score, AIC_score, BIC_score
import warnings
warnings.filterwarnings('ignore')
import statsmodels.api as sm
import statsmodels.formula.api as sm

no display found. Using non-interactive Agg backend

In [2]:
car_df= pd.read_csv('ToyotaCorolla.csv')

In [3]:
car_df.dtypes

Id                    int64
Model                object
Price                 int64
Age_08_04             int64
Mfg_Month             int64
Mfg_Year              int64
KM                    int64
Fuel_Type            object
HP                    int64
Met_Color             int64
Color                object
Automatic             int64
CC                    int64
Doors                 int64
Cylinders             int64
Gears                 int64
Quarterly_Tax         int64
Weight                int64
Mfr_Guarantee         int64
BOVAG_Guarantee       int64
Guarantee_Period      int64
ABS                   int64
Airbag_1              int64
Airbag_2              int64
Airco                 int64
Automatic_airco       int64
Boardcomputer         int64
CD_Player             int64
Central_Lock          int64
Powered_Windows       int64
Power_Steering        int64
Radio                 int64
Mistlamps             int64
Sport_Model           int64
Backseat_Divider      int64
Metallic_Rim          int64
Radio_cassette        int64
Parking_Assistant     int64
Tow_Bar               int64
dtype: object

In [4]:
predictors = ['Age_08_04', 'KM', 'Fuel_Type', 'HP', 'Automatic', 'Airco', 
              'Doors', 'Quarterly_Tax', 'Automatic_airco','Mfr_Guarantee','Guarantee_Period','CD_Player','Powered_Windows','Sport_Model','Tow_Bar']
outcome = 'Price'

In [5]:
#Creating dummies
X = pd.get_dummies(car_df[predictors], drop_first=True)
Y = car_df[outcome]

In [6]:
#Splitting the data into training, test and validation
train_X, valid_X, train_Y, valid_Y = train_test_split(X, Y, test_size=0.5, random_state=1)
test_X, valix_X, test_Y, valid_Y = train_test_split(valid_X, valid_Y, test_size=0.6, random_state=1)
print('Training :', train_X.shape)
print('Validation :', valid_X.shape)
print('Test :',test_X.shape)

Training : (718, 16)
Validation : (718, 16)
Test : (287, 16)

In [7]:
train_X

,Age_08_04,KM,HP,Automatic,Airco,Doors,Quarterly_Tax,Automatic_airco,Mfr_Guarantee,Guarantee_Period,CD_Player,Powered_Windows,Sport_Model,Tow_Bar,Fuel_Type_Diesel,Fuel_Type_Petrol
780,61,76700,86,0,0,5,69,0,0,3,0,0,1,0,0,1
1010,60,36943,110,0,0,5,85,0,1,3,0,0,1,1,0,1
1426,78,30964,110,1,1,3,85,0,1,12,0,0,0,1,0,1
1405,76,45410,86,0,0,5,69,0,1,3,0,0,0,0,0,1
1282,80,73200,110,0,0,5,85,0,0,3,0,1,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
715,62,90000,110,0,0,3,69,0,0,3,0,0,1,0,0,1
905,65,59000,110,0,0,3,69,0,0,3,0,0,0,0,0,1
1096,75,125400,110,0,0,3,69,0,0,6,0,1,0,0,0,1
235,38,60829,110,0,0,5,85,0,1,3,0,0,0,0,0,1
1061,78,161775,86,0,0,3,69,0,0,3,0,1,1,0,0,1

In [8]:
valid_X

,Age_08_04,KM,HP,Automatic,Airco,Doors,Quarterly_Tax,Automatic_airco,Mfr_Guarantee,Guarantee_Period,CD_Player,Powered_Windows,Sport_Model,Tow_Bar,Fuel_Type_Diesel,Fuel_Type_Petrol
509,46,53700,97,0,0,5,85,0,1,3,1,1,0,0,0,1
435,53,79800,110,0,0,5,85,0,1,3,0,0,0,0,0,1
321,36,36269,110,0,1,5,85,0,0,3,1,1,0,1,0,1
1055,70,178800,72,0,0,3,185,0,0,3,0,0,1,0,1,0
288,44,44218,97,0,0,5,85,0,1,3,1,0,0,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
483,56,62751,110,0,1,3,69,0,0,3,0,0,1,1,0,1
282,39,45713,97,0,1,5,19,0,0,6,1,1,0,0,0,1
437,48,78600,110,0,0,5,85,0,0,3,0,1,0,0,0,1
863,60,64383,86,0,0,3,69,0,1,3,0,0,0,0,0,1
548,56,43700,86,0,1,3,69,0,1,3,0,1,0,0,0,1

In [9]:
train_Y

780      9950
1010     9500
1426     9950
1405     7750
1282     7500
        ...
715      8490
905      9950
1096     7900
235     11650
1061     5800
Name: Price, Length: 718, dtype: int64

In [10]:
valid_Y.describe()

count      431.000000
mean     10540.737819
std       3402.888762
min       4350.000000
25%       8500.000000
50%       9750.000000
75%      11500.000000
max      31275.000000
Name: Price, dtype: float64

In [11]:
car_df.isnull().values.any()

False

In [12]:
car_lm = LinearRegression()
car_lm.fit(train_X, train_Y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [13]:
# print coefficients
print('intercept ', car_lm.intercept_)
print(pd.DataFrame({'Predictor': X.columns, 'coefficient': car_lm.coef_}))

# print performance measures
regressionSummary(train_Y, car_lm.predict(train_X))

intercept  8998.528552931193
           Predictor  coefficient
0          Age_08_04  -112.139772
1                 KM    -0.019437
2                 HP    39.474311
3          Automatic   583.265499
4              Airco    45.831357
5              Doors   214.445095
6      Quarterly_Tax    17.192451
7    Automatic_airco  2956.041165
8      Mfr_Guarantee   129.110109
9   Guarantee_Period    77.305623
10         CD_Player   276.496513
11   Powered_Windows   521.606032
12       Sport_Model   517.807321
13           Tow_Bar  -267.478660
14  Fuel_Type_Diesel  2163.735433
15  Fuel_Type_Petrol  1968.284558

Regression statistics

                      Mean Error (ME) : -0.0000
       Root Mean Squared Error (RMSE) : 1235.9139
            Mean Absolute Error (MAE) : 914.8383
          Mean Percentage Error (MPE) : -0.9286
Mean Absolute Percentage Error (MAPE) : 8.9407

In [14]:
pred_Y = car_lm.predict(train_X)

print('adjusted r2 : ', adjusted_r2_score(train_Y, pred_Y, car_lm))
print('AIC : ', AIC_score(train_Y, pred_Y, car_lm))
print('BIC : ', BIC_score(train_Y, pred_Y, car_lm))

adjusted r2 :  0.8906399861551406
AIC :  12297.2924259895
BIC :  12379.668878232369

In [15]:
# PART-A: Compurting the coefficicient of correlation between the predictor and the outcome.Higher correaltion means that we can
#choose that predictor to predict our target variable
cc = car_df[["Price", "Age_08_04"]].corr()
print(cc)
cc = car_df[["Price", "KM"]].corr()
print(cc)
cc = car_df[["Price", "HP"]].corr()
print(cc)
cc = car_df[["Price", "Automatic"]].corr()
print(cc)
cc = car_df[["Price", "Airco"]].corr()
print(cc)
cc = car_df[["Price", "Doors"]].corr()
print(cc)
cc = car_df[["Price", "Quarterly_Tax"]].corr()
print(cc)
cc = car_df[["Price", "Automatic_airco"]].corr()
print(cc)
cc = car_df[["Price", "Mfr_Guarantee"]].corr()
print(cc)
cc = car_df[["Price", "Guarantee_Period"]].corr()
print(cc)
cc = car_df[["Price", "CD_Player"]].corr()
print(cc)
cc = car_df[["Price", "Powered_Windows"]].corr()
print(cc)
cc = car_df[["Price", "Sport_Model"]].corr()
print(cc)
cc = car_df[["Price", "Tow_Bar"]].corr()
print(cc)

             Price  Age_08_04
Price      1.00000   -0.87659
Age_08_04 -0.87659    1.00000
         Price       KM
Price  1.00000 -0.56996
KM    -0.56996  1.00000
         Price       HP
Price  1.00000  0.31499
HP     0.31499  1.00000
              Price  Automatic
Price      1.000000   0.033081
Automatic  0.033081   1.000000
          Price     Airco
Price  1.000000  0.429259
Airco  0.429259  1.000000
          Price     Doors
Price  1.000000  0.185326
Doors  0.185326  1.000000
                  Price  Quarterly_Tax
Price          1.000000       0.219197
Quarterly_Tax  0.219197       1.000000
                    Price  Automatic_airco
Price            1.000000         0.588262
Automatic_airco  0.588262         1.000000
                  Price  Mfr_Guarantee
Price          1.000000       0.197802
Mfr_Guarantee  0.197802       1.000000
                     Price  Guarantee_Period
Price             1.000000          0.146627
Guarantee_Period  0.146627          1.000000
              Price  CD_Player
Price      1.000000   0.481374
CD_Player  0.481374   1.000000
                    Price  Powered_Windows
Price            1.000000         0.356518
Powered_Windows  0.356518         1.000000
                Price  Sport_Model
Price        1.000000     0.164121
Sport_Model  0.164121     1.000000
            Price   Tow_Bar
Price    1.000000 -0.172369
Tow_Bar -0.172369  1.000000

In [16]:
#PART-B
#Splitting the dataset into training and validation as 60-40
train_X, valid_X, train_Y, valid_Y = train_test_split(X, Y, test_size=0.4, random_state=1)

In [17]:
car_lm = LinearRegression()
car_lm.fit(train_X, train_Y)
print('intercept ', car_lm.intercept_)
print(pd.DataFrame({'Predictor': X.columns, 'coefficient': car_lm.coef_}))

intercept  9391.218475310365
           Predictor  coefficient
0          Age_08_04  -110.189172
1                 KM    -0.019544
2                 HP    35.756835
3          Automatic   655.613809
4              Airco    83.694732
5              Doors   220.631699
6      Quarterly_Tax    16.169935
7    Automatic_airco  3004.084172
8      Mfr_Guarantee   142.907233
9   Guarantee_Period    74.011715
10         CD_Player   348.574639
11   Powered_Windows   516.794680
12       Sport_Model   478.372120
13           Tow_Bar  -213.312422
14  Fuel_Type_Diesel  1980.028708
15  Fuel_Type_Petrol  1857.645507

In [18]:
pred_Y = car_lm.predict(train_X)

print('adjusted r2 : ', adjusted_r2_score(train_Y, pred_Y, car_lm))
print('AIC : ', AIC_score(train_Y, pred_Y, car_lm))
print('BIC : ', BIC_score(train_Y, pred_Y, car_lm))

adjusted r2 :  0.8895462078039181
AIC :  14717.395639763638
BIC :  14803.041340843336

In [19]:
# Use predict() to make predictions on a new set
car_lm_pred = car_lm.predict(valid_X)

result = pd.DataFrame({'Predicted': car_lm_pred, 'Actual': valid_Y,
                       'Residual': valid_Y - car_lm_pred})
print(result.head(20))

# Compute common accuracy measures
regressionSummary(valid_Y, car_lm_pred)

         Predicted  Actual     Residual
509   12306.989947   10900 -1406.989947
435   10625.043234   10895   269.956766
321   13941.862815   10750 -3191.862815
1055   7091.813860    6500  -591.813860
288   11982.575087   11895   -87.575087
48    17084.575260   17950   865.424740
1403   7354.205624    7000  -354.205624
952    9551.947336    8400 -1151.947336
1097   8145.533597    7250  -895.533597
204   12175.447926   12950   774.552074
978    9605.069123    8745  -860.069123
404    9513.988947    9450   -63.988947
1338   7429.091483    7499    69.908517
754    9035.502540    9950   914.497460
1189   6929.952200    8500  1570.047800
948    7794.924700    7750   -44.924700
1079   5353.116039    8950  3596.883961
1108   8121.533818    8250   128.466182
107   16477.341547   17450   972.658453
1065   5660.641018    6550   889.358982

Regression statistics

                      Mean Error (ME) : 66.0755
       Root Mean Squared Error (RMSE) : 1197.2318
            Mean Absolute Error (MAE) : 929.5707
          Mean Percentage Error (MPE) : -0.1101
Mean Absolute Percentage Error (MAPE) : 9.3825

In [20]:
#determining residuals
car_lm_pred = car_lm.predict(valid_X)
all_residuals = valid_Y - car_lm_pred

# Determine the percentage of datapoints with a residual in [-1500, 1500] = approx. 83\%
print(len(all_residuals[(all_residuals > -1500) & (all_residuals < 1500)]) / len(all_residuals))

ax = pd.DataFrame({'Residuals': all_residuals}).hist(bins=25)
plt.tight_layout()
plt.savefig("myexample.png")

0.8278260869565217

In [21]:
train_df = train_X.join(train_Y)

predictors = train_X.columns
formula = 'Price ~ ' + ' + '.join(predictors)

car_lm = sm.ols(formula=formula, data=train_df).fit()
print(car_lm.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                  Price   R-squared:                       0.892
Model:                            OLS   Adj. R-squared:                  0.890
Method:                 Least Squares   F-statistic:                     433.9
Date:                Tue, 16 Jun 2020   Prob (F-statistic):               0.00
Time:                        11:22:23   Log-Likelihood:                -7340.7
No. Observations:                 861   AIC:                         1.472e+04
Df Residuals:                     844   BIC:                         1.480e+04
Df Model:                          16
Covariance Type:            nonrobust
====================================================================================
                       coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------
Intercept         9391.2185    724.787     12.957      0.000    7968.622    1.08e+04
Age_08_04         -110.1892      3.590    -30.694      0.000    -117.235    -103.143
KM                  -0.0195      0.002    -12.299      0.000      -0.023      -0.016
HP                  35.7568      3.780      9.460      0.000      28.338      43.176
Automatic          655.6138    175.600      3.734      0.000     310.951    1000.277
Airco               83.6947    106.491      0.786      0.432    -125.324     292.713
Doors              220.6317     46.601      4.735      0.000     129.165     312.098
Quarterly_Tax       16.1699      2.089      7.740      0.000      12.069      20.271
Automatic_airco   3004.0842    209.454     14.342      0.000    2592.972    3415.196
Mfr_Guarantee      142.9072     90.786      1.574      0.116     -35.285     321.099
Guarantee_Period    74.0117     15.187      4.873      0.000      44.202     103.821
CD_Player          348.5746    121.993      2.857      0.004     109.129     588.020
Powered_Windows    516.7947    103.466      4.995      0.000     313.713     719.876
Sport_Model        478.3721     97.313      4.916      0.000     287.369     669.375
Tow_Bar           -213.3124     99.931     -2.135      0.033    -409.454     -17.171
Fuel_Type_Diesel  1980.0287    448.760      4.412      0.000    1099.213    2860.844
Fuel_Type_Petrol  1857.6455    482.307      3.852      0.000     910.984    2804.307
==============================================================================
Omnibus:                      152.110   Durbin-Watson:                   2.011
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              558.080
Skew:                           0.805   Prob(JB):                    6.52e-122
Kurtosis:                       6.601   Cond. No.                     1.64e+06
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.64e+06. This might indicate that there are
strong multicollinearity or other numerical problems.